### ISSUE TITLE
Other genes

### ISSUE THREAD

**Issue by dnil** [moonso/stranger#24]
Add HOXD13, HOXA13, FOXL2, LRP12, MUC1, EIF4A3, ... 
See https://www.ncbi.nlm.nih.gov/books/NBK535148/

**Comment by katerinaoleynikova** [comment]
Hi,

as far as I can see, there is no MUC1 locus in variant catalog. 
thanks.

**Comment by dnil** [comment]
Hi, 

thank you kindly for getting in touch!

That is true. If I got the literature right, that is basically a homopolymer followed by a single base insertion C, like C(7) is healthy and C(8) affected. Also ins(A) at the same spot are affected? As such it is not so much a tandem repeat expansion or VNTR, more like a SNV from a base calling perspective.

Do you have any positive patient samples to check this in? If so we could try both ExHu and a regular variant caller like GATK or DeepVariant on it and see how that goes? The ExHu folks may very well be interested in doing a specialised call for it, like for SMN or CYP, if it would turn out to fail regular SNV calling - or we could perhaps also do something along those lines.

All the best!
