### ISSUE TITLE
GLS ReferenceRegion for GRCh37

### ISSUE THREAD

**Issue by bw2** [moonso/stranger#33]
Thank you for making these variant catalogs publicly available!
I think the [GLS GRCh37 coordinates](https://github.com/moonso/stranger/blob/master/stranger/resources/variant_catalog_grch37.json#L977) should be  `2:191745598-191745646`  based on [liftover from GRCh38](https://liftover.broadinstitute.org/#input=2%3A190880872-190880920&hg=hg38-to-hg19)

**Comment by dnil** [comment]
And thank you for taking the time to correct it! Super - most grateful!
