### ISSUE TITLE
RFC1 ReferenceRegion for GRCh37

### ISSUE THREAD

**Issue by bw2** [moonso/stranger#34]
Similarly, the [start coordinate for RFC1](https://github.com/moonso/stranger/blob/master/stranger/resources/variant_catalog_grch37.json#L994) appears to be 1 off on GRCh37. 
The 0-based coordinates should be `chr4:39,350,044-39,350,099`.

**Comment by dnil** [comment]
That indeed appears to be the case. Thank you again!
