### ISSUE TITLE
different attributes in GRCh37 vs. GRCh38 catalogs

### ISSUE THREAD

**Issue by bw2** [moonso/stranger#36]
A few more details that might need some clarification:

These 4 loci have different `NormalMax` values in 37 vs. 38 (and ATN1 also has different `PathologicMin`):
```
ATN1 35 34
DMPK 34 37
FMR1 55 65
TBP 40 44
```

These loci have differing `LocusStructure` (even though DisplayRU is the same):
```
TBP (CAN)* (GCA)*
NIPA1 (NGC)* (GCG)*
```

TBP locus GRCh38 coordinates match the EHv4 catalog coordinates (https://github.com/Illumina/ExpansionHunter/blob/master/variant_catalog/hg38/variant_catalog.json#L499)
but the GRCh37 coordinates don't match the EHv4 catalog (https://github.com/Illumina/ExpansionHunter/blob/master/variant_catalog/hg19/variant_catalog.json#L260) 

The situation is the same for NIPA1.

**Comment by dnil** [comment]
Thank you kindly! Most is just lack of proofreading, but e.g. TBP and NIPA1 appear connected to incomplete merging in of the loci from ExpansionHunter as they are tested and added. We would as a general rule always try to keep the ExHu ones if they exist, for best compatibility and most testing. Note the eg tendency for us to be biased by the established clinical repeat unit in delimiting the units. And the lack of a scripted comparison test for liftOver operations. 😬

**Comment by dnil** [comment]
Again, thank you for the feedback. I have added a couple of validation scripts that will help keep the number of variant catalog genome build out of sync mistakes down. The off-by-one 0-based start to appear a common theme as well, so I will have to go on a separate ob1-hunt with REViewer. The usual effect is just an ugly gap in the alignment between the last anchor base and the first graph model one, but why not get it right. I will call it a night now before I make more mistakes. Cheers!
