### ISSUE TITLE
Review HGNCId - LocusId associations

### ISSUE THREAD

**Issue by ehre** [moonso/stranger#37]
Somehow mistakes have been made for the associations between gene names (LocusId) and HGNCid. We discovered this in Lund when a gene panel contained only the gene CBL but the STR module displayed results for both CBL and BEAN1. At a quick review I notice that BEAN1 and CBL both have assigned HGNCId 1541 (correct for CBL but not for BEAN1). Further down in the stranger list CSTB and DAB1 both have 2482 (correct for CSTB but not for DAB1). It's possible that there are more discrepancies, I haven't done a systematic check, so please review the entire catalog.

**Comment by dnil** [comment]
Thank you - well spotted! We will correct them and run a check for the others before releasing a new version.

**Comment by dnil** [comment]
I have now also added a couple of verification scripts for the variant catalogs, one of which will check HGNCId and gene symbol against genenames.org (HGNC) so we hopefully don't have this again. Also note that the DAB1 RU was pretty bad as well - a revcomp mistake. And BEAN1 is still untested for lack of a positive control. 

Just throwing a thought out: are you well on top of which ones are highly uncertain (I guess basically the ones you would not have DNA on the shelf for) or would it help if we device some kind of notation marking which ones have seen more proper verification?

**Comment by ehre** [comment]
I think a "verification flag" may be helpful.
