### ISSUE TITLE
Add refs field to json file

### ISSUE THREAD

**Issue by moonso** [moonso/stranger#5]
We should add a list that points to references that supports the repeat and/or the levels of pathogenicity. References could be urls to for example OMIM or pubmed. What do you think of that @dnil ? This would make the whole thing more transparent and trackable. I'll be happy to help out with this of course.

**Comment by dnil** [comment]
Sure, be my guest! :wink: No, but I agree of course, and have thought about it. Perfect if you have the momentum to start on it: I should be able to help with missing ones - I found something on all that have numbers now at leat..

**Comment by moonso** [comment]
Ok, could you send me a list or how should we proceed?

**Comment by dnil** [comment]
I added a reference for the latest one I read about, NIPA1. We can go over old ones at some points and add references for new loci as we go along.

**Comment by moonso** [comment]
Tomorrow perhaps?

**Comment by dnil** [comment]
If we have time: it is hardly urgent.
